# Generated by Django 2.0.6 on 2018-11-19 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface_app', '0002_remove_testcase_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testcase',
            old_name='reponses_assert',
            new_name='resp_assert',
        ),
    ]
