# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itest', '0003_apimodules'),
    ]

    operations = [
        migrations.AddField(
            model_name='apimodules',
            name='parentId',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
