# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 14:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itest', '0004_apimodules_parentid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiDefine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('url', models.CharField(max_length=600)),
                ('method', models.CharField(max_length=20)),
                ('dec', models.TextField()),
                ('header', models.TextField()),
                ('parmasType', models.CharField(max_length=30)),
                ('parmas', models.TextField()),
                ('parmasExample', models.TextField()),
                ('responseStatus', models.CharField(max_length=20)),
                ('responseType', models.CharField(max_length=30)),
                ('response', models.CharField(max_length=30)),
                ('responseExample', models.TextField()),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itest.ApiModules')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itest.Project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itest.Users')),
            ],
        ),
    ]
