# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-11 16:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itest', '0005_apidefine'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonParmasModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('type', models.CharField(max_length=60)),
                ('value', models.TextField()),
                ('default', models.TextField()),
                ('dec', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='dataModal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TestCaseDataModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.TextField()),
                ('parmas', models.TextField()),
                ('responseStatus', models.TextField()),
                ('assertResponseHead', models.TextField()),
                ('assertResponseBody', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TestCaseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('dec', models.TextField()),
                ('globalTestData', models.IntegerField()),
                ('testDataList', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='apidefine',
            name='response',
            field=models.TextField(),
        ),
        migrations.AddField(
            model_name='testcasemodel',
            name='api',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itest.ApiDefine'),
        ),
        migrations.AddField(
            model_name='testcasemodel',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itest.ApiModules'),
        ),
        migrations.AddField(
            model_name='testcasemodel',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itest.Project'),
        ),
        migrations.AddField(
            model_name='testcasemodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itest.Users'),
        ),
        migrations.AddField(
            model_name='testcasedatamodel',
            name='testCase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itest.TestCaseModel'),
        ),
        migrations.AddField(
            model_name='datamodal',
            name='testCase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itest.TestCaseDataModel'),
        ),
        migrations.AddField(
            model_name='commonparmasmodel',
            name='api',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itest.ApiDefine'),
        ),
    ]
