# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-14 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itest', '0011_auto_20170913_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcasemodel',
            name='dataType',
            field=models.IntegerField(default=1),
        ),
    ]
