# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-15 17:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itest', '0012_testcasemodel_datatype'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestSuiteModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('dec', models.TextField(default='')),
                ('preSql', models.TextField(default='')),
                ('postSql', models.TextField(default='')),
                ('casesId', models.TextField(default='')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itest.Project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itest.Users')),
            ],
        ),
    ]
