# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-20 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itest', '0015_testcasemodel_prevaluepicker'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcasemodel',
            name='sqlAssert',
            field=models.TextField(default=''),
        ),
    ]
