# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-22 12:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itest', '0016_testcasemodel_sqlassert'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseSettingModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=500)),
                ('user', models.CharField(max_length=100)),
                ('psw', models.CharField(max_length=100)),
                ('database', models.CharField(max_length=100)),
                ('port', models.IntegerField(default=3306)),
                ('sshHost', models.CharField(max_length=500)),
                ('sshUser', models.CharField(max_length=100)),
                ('sshPsw', models.CharField(max_length=100)),
                ('sshPort', models.IntegerField(default=22)),
                ('sshKey', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='EnvModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itest.Project')),
            ],
        ),
        migrations.AddField(
            model_name='databasesettingmodel',
            name='env',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itest.EnvModel'),
        ),
        migrations.AddField(
            model_name='databasesettingmodel',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itest.Project'),
        ),
        migrations.AddField(
            model_name='golbalvaluesmodel',
            name='env',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='itest.EnvModel'),
            preserve_default=False,
        ),
    ]
