# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-25 19:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itest', '0017_auto_20170922_1208'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='golbalValuesModel',
            new_name='GlobalValuesModel',
        ),
    ]
