# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-26 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itest', '0018_auto_20170925_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='databasesettingmodel',
            name='type',
            field=models.CharField(default='mysql', max_length=50),
        ),
    ]
