# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-26 16:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itest', '0019_databasesettingmodel_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PickerValuesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=50)),
                ('expression', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='RequirementModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sql', models.TextField(default='')),
                ('pickerValue', models.TextField(default='[]')),
                ('type', models.CharField(max_length=30)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itest.TestCaseModel')),
            ],
        ),
        migrations.RemoveField(
            model_name='commonparmasmodel',
            name='api',
        ),
        migrations.AddField(
            model_name='testsuitemodel',
            name='postRequirement',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='testsuitemodel',
            name='preRequirement',
            field=models.TextField(default='[]'),
        ),
    ]
