# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-28 18:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itest', '0020_auto_20170926_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testsuitemodel',
            name='preCases',
        ),
        migrations.RemoveField(
            model_name='testsuitemodel',
            name='valuePicker',
        ),
    ]
