# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-29 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itest', '0021_auto_20170928_1829'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomizeAssertModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('key', models.TextField(default='')),
                ('value', models.TextField(default='')),
                ('type', models.IntegerField(default=0)),
                ('sql', models.TextField(default='')),
                ('sqlAssert', models.TextField(default='')),
                ('assertType', models.CharField(default='common', max_length=20)),
            ],
        ),
    ]
