# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-30 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itest', '0022_customizeassertmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcasemodel',
            name='postRequirement',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='testcasemodel',
            name='preRequirement',
            field=models.TextField(default='[]'),
        ),
    ]
