# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-13 16:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itest', '0023_auto_20170930_1426'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('taskType', models.IntegerField(default=0)),
                ('repeatDateTime', models.DateTimeField()),
                ('repeatType', models.IntegerField(default=-1)),
                ('status', models.IntegerField(default=0)),
                ('successRate', models.IntegerField(default=0)),
                ('currentResultMark', models.IntegerField(default=-1)),
                ('env', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itest.EnvModel')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itest.Project')),
                ('suite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itest.TestSuiteModel')),
            ],
        ),
    ]
