# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-16 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itest', '0024_taskmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='lastRunningTime',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
