# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-18 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itest', '0027_taskmodel_lastrunninguser'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='lastRunningSuccessCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='lastRunningfailedCount',
            field=models.IntegerField(default=0),
        ),
    ]
