# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-18 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itest', '0028_auto_20171018_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='lastRunningResultIdList',
            field=models.TextField(default='[]'),
        ),
    ]
