# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-23 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itest', '0031_testcaseresultmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskmodel',
            name='currentResultVersion',
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='lastRunningPreResultIdList',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='nextResultVersion',
            field=models.IntegerField(default=0),
        ),
    ]
