# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-23 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itest', '0032_auto_20171023_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcaseresultmodel',
            name='responseStatus',
            field=models.CharField(default='200', max_length=10),
        ),
    ]
