# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-25 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itest', '0033_testcaseresultmodel_responsestatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcaseresultmodel',
            name='postSql',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='testcaseresultmodel',
            name='preSql',
            field=models.TextField(default=''),
        ),
    ]
