# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-25 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itest', '0034_auto_20171025_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcaseresultmodel',
            name='caseId',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='testcaseresultmodel',
            name='taskId',
            field=models.IntegerField(default=-1),
        ),
    ]
