# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-26 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itest', '0035_auto_20171025_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcaseresultmodel',
            name='method',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='testcaseresultmodel',
            name='url',
            field=models.TextField(default=''),
        ),
    ]
