# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-26 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itest', '0036_auto_20171026_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcaseresultmodel',
            name='parmasType',
            field=models.CharField(default='', max_length=50),
        ),
    ]
