# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-27 18:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itest', '0037_testcaseresultmodel_parmastype'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskHistoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskId', models.IntegerField(default=-1)),
                ('taskName', models.CharField(max_length=100)),
                ('suiteId', models.IntegerField(default=-1)),
                ('envId', models.IntegerField(default=-1)),
                ('taskType', models.IntegerField(default=0)),
                ('repeatDateTime', models.DateTimeField()),
                ('repeatType', models.IntegerField(default=-1)),
                ('status', models.IntegerField(default=0)),
                ('successRate', models.IntegerField(default=0)),
                ('nextResultVersion', models.IntegerField(default=0)),
                ('lastResultVersion', models.IntegerField(default=-1)),
                ('lastRunningTime', models.CharField(max_length=100)),
                ('lastRunningUser', models.CharField(max_length=100)),
                ('lastRunningSuccessCount', models.IntegerField(default=0)),
                ('lastRunningfailedCount', models.IntegerField(default=0)),
                ('lastRunningResultIdList', models.TextField(default='[]')),
                ('lastRunningPreResultIdList', models.TextField(default='[]')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itest.Project')),
            ],
        ),
    ]
