# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-03 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itest', '0038_taskhistorymodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='pwd',
            field=models.CharField(max_length=20, verbose_name='\u5bc6\u7801'),
        ),
        migrations.AlterField(
            model_name='users',
            name='user',
            field=models.CharField(max_length=30, verbose_name='\u540d\u79f0'),
        ),
    ]
