# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-03 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itest', '0039_auto_20171103_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='Token',
            field=models.CharField(max_length=100, verbose_name='token'),
        ),
        migrations.AlterField(
            model_name='token',
            name='expireDate',
            field=models.DateTimeField(verbose_name='\u8fc7\u671f\u65f6\u95f4'),
        ),
    ]
