# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-03 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itest', '0040_auto_20171103_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testsuitemodel',
            name='casesId',
            field=models.TextField(default='', verbose_name='\u5173\u8054\u7684\u6848\u4f8bid'),
        ),
        migrations.AlterField(
            model_name='testsuitemodel',
            name='dec',
            field=models.TextField(default='', verbose_name='\u63cf\u8ff0'),
        ),
        migrations.AlterField(
            model_name='testsuitemodel',
            name='name',
            field=models.CharField(max_length=60, verbose_name='\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='testsuitemodel',
            name='postRequirement',
            field=models.TextField(default='[]', verbose_name='\u540e\u7f6e\u6761\u4ef6'),
        ),
        migrations.AlterField(
            model_name='testsuitemodel',
            name='postSql',
            field=models.TextField(default='', verbose_name='\u540e\u7f6esql'),
        ),
        migrations.AlterField(
            model_name='testsuitemodel',
            name='preRequirement',
            field=models.TextField(default='[]', verbose_name='\u524d\u7f6e\u6761\u4ef6'),
        ),
        migrations.AlterField(
            model_name='testsuitemodel',
            name='preSql',
            field=models.TextField(default='', verbose_name='\u524d\u7f6esql'),
        ),
    ]
