# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-22 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itest', '0041_auto_20171103_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskhistorymodel',
            name='lastRunningResult',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='lastRunningResult',
            field=models.TextField(default='\u65e0\u7ed3\u679c'),
        ),
        migrations.AddField(
            model_name='testcaseresultmodel',
            name='message',
            field=models.TextField(default='\u6267\u884c\u5b8c\u6210'),
        ),
        migrations.AlterField(
            model_name='taskhistorymodel',
            name='taskId',
            field=models.IntegerField(db_index=True, default=-1),
        ),
        migrations.AlterField(
            model_name='testcaseresultmodel',
            name='taskId',
            field=models.IntegerField(db_index=True, default=-1),
        ),
        migrations.AlterField(
            model_name='testcaseresultmodel',
            name='version',
            field=models.IntegerField(db_index=True, default=-1),
        ),
        migrations.AlterField(
            model_name='token',
            name='Token',
            field=models.CharField(db_index=True, max_length=100, verbose_name='token'),
        ),
    ]
